### ISSUE TITLE
Strip `nofail` option in mount.fuse helper

### ISSUE THREAD

**Issue by jsoref** [libfuse/libfuse#211]
Please excuse my ignorance.

I hit https://github.com/systemd/systemd/issues/5032 and they said it isn't their fault.

Here's the original bug report (by @vicinus):

### Expected behaviour you didn't see

> I want to use the nofail option in /etc/fstab to ensure that the boot up process is finished and no emergency mode is entered on trying to mount some fuse.bindfs mounts during boot up.

> It should be possible to use the nofail option in /etc/fstab with all types of filesystems.

### Unexpected behaviour you saw

> The Problem is, that the nofail option is passed by the mount command line tool to the mount tool specific to the filesystem type and fuse.bindfs based filesystems do not support the nofail option and therefore fail, which is rater ironically...

> One possible solution would be to add x-systemd.nofail and x-systemd.fail with the behaviour to override an eventually existing nofail and fail option. As the new options are systemd specific they will not be passed to filesystem type specific mount tool and can therefore be safely used filesystem type specific mount tool does not support nofail.
In case of bug report: Steps to reproduce the problem

> Install bindfs and add a line like:

> `/usr /mnt fuse.bindfs defaults,nofail 0 0`

> Try to mount it and the error message is:

> `fuse: unknown option 'nofail'`

> Without the option nofail the mount works fine.

### Below are details from my system

```
Ubuntu 16.04.3 LTS
ii  libsystemd0:amd64                  229-4ubuntu19          amd64                  systemd utility library
ii  systemd                            229-4ubuntu19          amd64                  system and service manager
ii  systemd-sysv                       229-4ubuntu19          amd64                  system and service manager - SysV links
ii  fuse                               2.9.4-1ubuntu3.1       amd64                  Filesystem in Userspace
ii  libfuse2:amd64                     2.9.4-1ubuntu3.1       amd64                  Filesystem in Userspace (library)
ii  sshfs                              2.5-1ubuntu1           amd64                  filesystem client based on SSH File Transfer Protocol
```

```fstab
sshfs#user@host:/usr/something/ /usr/something fuse defaults,noauto,allow_other,idmap=user,reconnect,ServerAliveInterval=15,ServerAliveCountMax=3,IdentityFile=~someone/.ssh/id_rsa,x-systemd.requires=/usr/prereq,nofail,x-systemd.automount
```

### System console output
```console
[   12.614072] systemd[1]: usr-something.automount: Failed to check directory /usr/something: No such file or directory
[   12.626540] systemd[1]: usr-something.automount: Failed to initialize automounter: No such file or directory
[   12.637418] systemd[1]: Failed to set up automount usr-something.automount.
[FAILED] Failed to set up automount usr-something.automount.
See 'systemctl status usr-something.automount' for details.
```

```
# mount /usr/something
fuse: unknown option `nofail'
```

**Comment by Nikratio** [comment]
Thanks for the report! The problem is that the `mount.fuse` helper doesn't know about this option. It should be relatively easy to fix. I assume you are using libfuse 2.x?

**Comment by jsoref** [comment]
Yes, 2.9.4 as noted above

**Comment by ShapeShifter499** [comment]
Is this fix good for everything that uses fuse?

**Comment by jsoref** [comment]
That's my hope. I'm waiting for it to be released and make its way into my system's distributions so that I can test it.
On the bright side, one can test w/o booting, it's sufficient to call the fuse mounter w/ -o nofail...

**Comment by Nikratio** [comment]
Fixed in a83cd72

**Comment by ShapeShifter499** [comment]
@Nikratio Can this be pushed as a release so Linux distros will pick up the change?

**Comment by Nikratio** [comment]
Certainly this will be included in the next release. But I'm not going to create a new release just for this one change.

**Comment by ShapeShifter499** [comment]
Alright then

**Comment by jammin84** [comment]
Was this ever released? 

I'm still experiencing this in debian buster running fuse 2.9.9-1

**Comment by jsoref** [comment]
https://github.com/libfuse/libfuse/commit/a83cd72f641671b71b8268b1765e449cae071f3e seems to indicate it's in fuse 3.2.2.

Looks like it's available as `fuse3` in buster and later:
https://packages.debian.org/buster/fuse3

I suspect like the reason there's a `fuse3` is that there are too many packages that still rely on libfuse2, so instead of packaging fuse3 as `fuse`, debian folks packaged it as a side-by-side compatible package family. (When this works, it's really nice, when it doesn't -- high `libcurl3`/`libcurl4`, it's ...)

**Comment by bugs181** [comment]
Just run of the mill software dev here, I don't know much about linux kernels, packages, etc.. I'm running into this issue on OpenMediaVault (which I believe runs Debian behind the hood) and a DAS. When my DAS is being worked on, or I'm swapping drives - the Mergerfs plugin complains about fuse not understanding the `nofail` option. I've added the `nofail` option to `/etc/fstab` by hand because otherwise OMV would not even boot if one the pooled drives was missing.

```
fuse: unknown option `nofail`
```

How would I go about fixing this issue?

**Comment by trapexit** [comment]
@bugs181 The way mergerfs "fails" differs depending on how you have it setup. Might be worth to bring your question to the discord server or mergerfs github.
